### ISSUE TITLE
Display function signature

### ISSUE THREAD

**Issue by sveale** [sveale/autocomplete-glsl#2]
Display function signature. Maybe use "label" to display this. 
If autocomplete+ supported showing different text than what it expanded to (ie. in the suggestions the complete function signature is shown, but upon expansion only the function name replaces prefix), see https://github.com/atom-community/autocomplete-plus/issues/223.

**Comment by joefitzgerald** [comment]
Today, the label is used to show this additional context. We are considering moving the label text into a tooltip (expanded by default) for the currently suggested item.

Insertion of the full function signature with placeholders for arguments is something we'd like to do with an anonymous snippet.
